### ISSUE TITLE
Failed to execute 'define' on 'CustomElementRegistry

### ISSUE THREAD

**Issue by riddik14** [phischdev/lovelace-mushroom-better-sliders#12]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Uncaught error from Chrome 125.0.0.0 on Mac OS 10.15.7 NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "mushroom-select" has already been used with this registry /hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:29:61 /hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:29:76 n (/hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:1:963) /hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:569:66

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: chrome 
- HA Version: 2024.06
- Mushroom: ultimate
```

### Anything else?

lovelace-mushroom file name identical of lovelace-mushroom-better-slider: meshroom.js and mushroom.js.gz ? can it is a problem for hassio's front end?

**Comment by BettySwallocks** [comment]
Following as I have this same issue appearing in logs, noticed since 2024.7 but could have been earlier. I can confirm it occurs with Chrome 126 and Firefox 127 for me.

```
Logger: frontend.js.latest.202407050
Source: components/system_log/__init__.py:333
First occurred: 11:01:47 (2 occurrences)
Last logged: 11:10:04

Uncaught error from Chrome 126.0.0.0 on Windows 10 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "mushroom-select" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /hacsfiles/lovelace-mushroom/mushroom.js:29:61 /hacsfiles/lovelace-mushroom/mushroom.js:29:76 n (/hacsfiles/lovelace-mushroom/mushroom.js:1:963) /hacsfiles/lovelace-mushroom/mushroom.js:569:66
Uncaught error from Firefox 127.0 on Windows 10 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "mushroom-select" has already been used with this registry 3900/</window.CustomElementRegistry.prototype.define (src/scoped-custom-element-registry.js:44:14) pt/</< (/hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:29:61) pt/< (/hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:29:76) n (/hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:1:963) /hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:569:66
```

**Comment by Zockerherz** [comment]
Hey Guys,

I have the same Error in my logs. :)


```
Logger: frontend.js.latest.202407100
Quelle: components/system_log/__init__.py:333
Erstmals aufgetreten: 07:47:41 (1 Vorkommnisse)
Zuletzt protokolliert: 07:47:41

Uncaught error from Edge 126.0.0.0 on Mac OS 10.15.7 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "mushroom-select" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:29:61 /hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:29:76 n (/hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:1:963) /hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:569:66
```

**Comment by topshelf510** [comment]
Same too, for the most part 😅

```

Logger: frontend.js.latest.202407100
Source: components/system_log/__init__.py:333
First occurred: August 4, 2024 at 11:15:49 PM (13 occurrences)
Last logged: 2:39:32 PM

Uncaught error from Mobile Safari 18.0 on iOS 18.1 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "mushroom-select" has already been used with this registry message (node_modules/core-js/modules/web.dom-exception.stack.js:25:24) src/scoped-custom-element-registry.js:45:10 /hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:29:67 n (/hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:1:964) module code (/hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:569:67)

```

**Comment by BlueForrest** [comment]
I have the same with Brave Browser: Any Idea how to fix this error?

Uncaught error from Brave 130.0.0.0 on Windows 10 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "mushroom-select" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:29:61 /hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:29:76 n (/hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:1:963) /hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:569:66

**Comment by rodgorlabach** [comment]
I also receive the same type of error
```

Logger: frontend.js.modern.202411062
Source: components/system_log/__init__.py:331
First occurred: 07:34:04 (6 occurrences)
Last logged: 11:06:10

Uncaught error from WebKit 605.1.15 on iOS 18.1.1 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "mushroom-select" has already been used with this registry message (node_modules/core-js/modules/web.dom-exception.stack.js:25:24) src/scoped-custom-element-registry.js:45:10 /hacsfiles/lovelace-mushroom/mushroom.js:23:132 Vr (/hacsfiles/lovelace-mushroom/mushroom.js:1:15070) module code (/hacsfiles/lovelace-mushroom/mushroom.js:286:46393)
Uncaught error from WebKit 605.1.15 on iOS 18.1.1 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "mushroom-select" has already been used with this registry message (node_modules/core-js/modules/web.dom-exception.stack.js:25:24) src/scoped-custom-element-registry.js:45:10 /local/mushroom.js:43:74 n (/local/mushroom.js:15:788) module code (/local/mushroom.js:595:45044)

```

**Comment by Trzinka** [comment]
I also receive the same type of error

```yaml
Logger: frontend.js.modern.202411276
Source: components/system_log/__init__.py:331
First occurred: 12:29:51 (1 occurrences)
Last logged: 12:29:51

Uncaught error from Chrome 131.0.0.0 on Windows 10 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "mushroom-select" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:29:61 /hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:29:76 n (/hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:1:963) /hacsfiles/lovelace-mushroom-better-sliders/mushroom.js:569:66
```
