### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by dolenec** [phischdev/lovelace-mushroom-better-sliders#5]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

The problem is that there is missing translation for text "off" which is not found on translation text in languages and neither in Home Assistant localize contributing under backend and frontend.

### Expected Behavior

off should be

English:
Off
Slovenian:
Izklopljeno

and so on..

![Screenshot_20230509_194950_Home Assistant](https://github.com/phischdev/lovelace-mushroom-better-sliders/assets/16633222/80caaa52-4205-4d6c-9501-263d36d07580)

### Context

YAML state
```
entities:
  - type: custom:mushroom-light-card
    entity: light.shelly_rgbw2_hodnik
    use_light_color: true
    show_brightness_control: true
    show_color_temp_control: true
    show_color_control: true
    collapsible_controls: false
    double_tap_action:
      action: more-info
    hold_action:
      action: more-info
show_header_toggle: false
type: entities
```

### Environment

```markdown
- Browser: all
- HA Version: 2023.5.2
- Mushroom: (latest) 2.6.1-1
```
